#!/bin/sh
rm -rf ./LipikaInputSource.app
rm ./com.daivajnanam.inputmethod.LipikaInputSource.pkg
rm ./LipikaInputSource.pkg
rm ./Scripts/installer
if [ "$1" == "clean" ]; then 
exit 0
fi
xcodebuild -project ../LipikaIME.xcodeproj -scheme Engine -configuration Debug clean build test || exit 1
killall LipikaInputSource
xcodebuild -project ../LipikaIME.xcodeproj -scheme InputSource -configuration Debug clean build test || exit 1
xcodebuild -project ../LipikaIME.xcodeproj -scheme InputSource -configuration Release clean build || exit 1
cp -r ../build/Products/Release/LipikaInputSource.app .
xcodebuild -project ../LipikaIME.xcodeproj -scheme PkgInstallTool -configuration Release clean build  || exit 1
cp ../build/Products/Release/installer ./Scripts/installer
pkgbuild --component LipikaInputSource.app --scripts ./Scripts --install-location /Library/Input\ Methods com.daivajnanam.inputmethod.LipikaInputSource.pkg
productbuild --distribution ./Distribution --package-path ./ --resources ./Resources --sign "Developer ID Installer: Ranganath Atreya (7JZ87Y4JWT)" LipikaInputSource.pkg
exit 0
